# FPC & Lazarus is built on each platform (takes ~10mins) then stored in cache.
# Cache is removed if not used in 7 days and is restricted to 5gb. Each lazarus install is ~300mb.

name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: 'Windows 32'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-i386-win32.exe'
            fpcup-opt: '--lazrevision=64339'
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'trunk'
            build-mode: 'WIN32'
            binary: 'libsimpleocr32.dll'

          - os: windows-latest
            name: 'Windows 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-win64.exe'
            fpcup-opt: '--lazrevision=64339'
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'trunk'
            build-mode: 'WIN64'
            binary: 'libsimpleocr64.dll'

          - os: ubuntu-latest
            name: 'Linux 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-linux'
            fpcup-opt: '--lazrevision=64339'
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'trunk'
            build-mode: 'LINUX64'
            binary: 'libsimpleocr64.so'

          - os: macos-latest
            name: 'MacOS 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-darwin'
            fpcup-opt: '--lazrevision=64339'
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'trunk'
            build-mode: 'DARWIN64'
            binary: 'libsimpleocr64.dylib'

          - os: ubuntu-latest
            name: 'AArch64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-linux'
            fpcup-opt: '--lazrevision=64339'
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'trunk'
            build-mode: 'AARCH64'
            binary: 'libsimpleocr64.so.aarch64'

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true

    - name: Install Dependencies (Ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install libgtk2.0-dev gcc-aarch64-linux-gnu
        sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib 
        
    - name: Generate Cache Hash
      run: echo "${{ matrix.config.fpcup-url }}${{ matrix.config.fpcup-opt }}${{ matrix.config.fpc-url }}${{ matrix.config.laz-url }}${{ matrix.config.name }}" > .cache

    - name: Cache
      id: cache
      uses: actions/cache@v2.1.4
      with:
        path: lazarus
        key: ${{ hashFiles('.cache') }}

    - name: Install Lazarus
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl --retry 5 -L -o fpcup ${{ matrix.config.fpcup-url }}
        chmod +x fpcup
        mkdir lazarus
        ./fpcup --installdir=lazarus --fpcURL=${{ matrix.config.fpc-url }} --lazURL=${{ matrix.config.laz-url }} ${{ matrix.config.fpcup-opt }} --only=docker --noconfirm --verbose

    - name: Install AArch64 Cross Compiler
      if: steps.cache.outputs.cache-hit != 'true' && matrix.config.name == 'AArch64'
      run: |
        curl --retry 5 -L -o libs.zip https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsLinuxAarch64.zip && unzip -o libs.zip -d lazarus/
        curl --retry 5 -L -o bins.zip https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.0/CrossBinsLinuxAarch64.zip && unzip -o bins.zip -d lazarus/cross/bin
        ./fpcup --installdir=lazarus --ostarget=linux --cputarget=aarch64 --only="FPCCleanOnly,FPCBuildOnly" --crossbindir=lazarus/cross/bin --crosslibdir=lazarus/cross/lib/aarch64-linux --noconfirm --verbose

    - name: Build SimpleOCR
      run: |
        ./lazarus/lazarus/lazbuild --build-mode=${{ matrix.config.build-mode }} "SimpleOCR.lpi"

    - name: Upload Artifact 
      uses: actions/upload-artifact@v2.2.2
      with:
        path: ${{ matrix.config.binary }}

  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for builds to complete
      uses: Brandon-T/wait-for-check-action@v1
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_names: '["Windows 32", "Windows 64", "Linux 64", "AArch64", "MacOS 64"]'
        statuses: '["completed", "completed", "completed", "completed", "completed"]'
        conclusions: '["success", "success", "success", "success", "success"]'
        timeout: 1500
        poll_interval: 5

    - name: Download Artifacts
      if: github.event_name == 'push'
      uses: actions/download-artifact@v2.0.8

    - name: Update Release
      if: github.event_name == 'push'
      uses: Brandon-T/update-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        suffix_branch_name: true
        release_name: 'autobuild'
        file: 'artifact/*'
        is_file_glob: true
        release_notes: "Binaries for the most recent commit of this branch. Don't worry about the release date, it's wrong!"
        tag: 'autobuild'
        retry_count: 5
        bump_tag: true
        overwrite: true